%--------------------------------------------------------------------------
% peakTwitchAmplitude_fit.m
% Author: Akira Nagamori
% Last update: 12/25/17
% ---Code descriptions-----
% Ojbective: find corrective factor for peak twitch amplitude to match
% predicted peak force produced by a given unit
%
%--------------------------------------------------------------------------
close all
clear all
clc

%--------------------------------------------------------------------------
% F0 parameters
density = 1.06; % muscle density [g/cm^3]
L0 = 6.8; % optimal muscle length [cm]
mass = 0.15; % muscle mass [kg]
PCSA = (mass*1000)/(density*L0); % PCSA of muscle
sigma = 31.8; % specific tension
F0 = PCSA*sigma;
N_fibers = 272850; % number of muscle fibers
N_MU = 450; % number of motor units
i_MU = 1:N_MU; % index for motor units

%--------------------------------------------------------------------------
% Peak tetanus parameter
RP_MU = 30; %range of peak tension across motor untis in unit of fold
b_MU = log(RP_MU)/N_MU; %coefficient to establish a range of twich force values
P_MU = exp(b_MU*i_MU); %force generated by a motor unit as a function of its recruitment threshold=
fPCSA = PCSA/N_fibers; % fractional PCSA occupied by a single fiber
ni = P_MU/sum(P_MU)*N_fibers; % innervation number of each unit assuming that peak tension generated by each unit is proportional to innervation number
Pi = sigma*fPCSA*ni; % peak tetanus amplitude of each unit
Pi_half = Pi./2; % half of peak tetanus amplitude of each unit
% load('cor_factor')
% Pi = Pi.*cor_factor';
%--------------------------------------------------------------------------
% Recruitment parameters
%   Find recruitment threshold for individual units using exponential fit
F_pcsa_slow = 0.5; % fractional PSCA of slow-twitch motor units (0-1)
[error, index_slow] = min(abs(cumsum(Pi) - F0*F_pcsa_slow)); % index for the largest motor unit clacified as slow-twitch
Ur = 0.8; % recruitment threshold for the last recruited motor unit
Ur_1 = 0.01; % reruitment threshold for the first unit
f_RT = fit([1 N_MU]',[Ur_1 Ur]','exp1');
coeffs_f_RT = coeffvalues(f_RT);
U_th = coeffs_f_RT(1)*exp(coeffs_f_RT(2)*i_MU); % the resulting recruitment threshold for individual units

%--------------------------------------------------------------------------
% Firing rate parameters
%   Find peak firing rates of individual units
%  In this formulation, the peak firing rate of a unit increases as
%  recruitment threshold increases (Loeb's formulation)
%  The minimum firing rate for individual units is constant as opposed to
%  Loeb's formulation
MFR_MU = 8; %muscle_parameter.MFR; %minimum firing rate constant for all motoneurons
PFR1_MU = 20; %the peak firing rate of the first recruited motoneuron in unit of impulse/sec
PFRD_MU = 40; %the desired difference in peak firing rates between the first and last units in unit of impulse/sec
RTEn_MU = U_th(end); %recruitment threshold of the last motor unit
PFR_MU = PFR1_MU + PFRD_MU * (U_th./RTEn_MU); %peak firing rate
FR_half = PFR_MU./2; % firing rate at which half of maximum tension is achieved

%--------------------------------------------------------------------------
% Contraction time and half relaxation time
%    Find contraction time and half relaxation time of individual units
%   Using Loeb's formulation that contraction time of individual units is
%   proportional to 1/FR_half (Brown & Loeb 2000 IV; Botterman et al., 1996)
CT_n = 20;
FR_half_n = FR_half(end);
CT = 1.5*(CT_n*FR_half_n)./FR_half;
CT = CT - (CT(end)-CT_n);
CT = CT/1000;
RT = CT;

%--------------------------------------------------------------------------
cv_MU = 0; %ISI variability as per coefficient of variation (=mean/SD)
Lce = 1;
Y = 1;
S = 0.96;
Af = 1;
Fs = 1000;
t_twitch = 0:1/Fs:1;
t_temp = 0:1/Fs:8;
t = 0:1/Fs:10;
count = 0;

testedUnits = [1 50 100 150 200 250 300 350 400 450]; % indeces for units tested
U = [zeros(1,Fs) ones(1,8*Fs) zeros(1,1*Fs+1)];

for k = 1:length(testedUnits)
    
    unitN = testedUnits(k);
    FR = PFR_MU(unitN);
    f_env = FR./FR_half(unitN);
    if testedUnits(k) <= index_slow 
        Af = Af_slow_function(f_env,Lce,Y);
        Af_cor = Af_slow_correction_function(f_env,Lce,Y);
    else
        Af = Af_fast_function(f_env,Lce,S);
        Af_cor = Af_fast_correction_function(f_env,Lce,S);
    end
    [twitch,T1,T2_temp] = twitch_function(f_env,Af,Lce,CT(unitN),RT(unitN),Fs);
    %twitch = Pi(unitN).*twitch*Af_cor;
    twitch = twitch*Af_cor;
    
    spikeTrain_temp = spikeTrainGenerator(t_temp,Fs,FR);
    spikeTrain = [zeros(1,1*Fs) spikeTrain_temp zeros(1,1*Fs)];
    
    force_temp = conv(spikeTrain,twitch);
    force = force_temp(1:length(t));
    meanForce = mean(force(5*Fs:7*Fs));
    %
    figure(1)
    plot(t,force)
    hold on
       
    maxForce(k) = meanForce;
    ratio(k) = Pi(unitN)/maxForce(k);
    
end

figure(2)
plot(testedUnits,maxForce)
title('Maximum Force')

figure(3)
plot(testedUnits,ratio)
title('Pi/Maximum Force')

x = testedUnits';
y = ratio';
f = fit(x,y,'smoothingspline');
figure(4)
plot(f,x,y)
xlabel('Motor Unit Number')
ylabel('Ratio') 
% 
cor_factor = feval(f,i_MU);

% save('cor_factor','cor_factor')
%%
function [twitch,T1,T2_temp] = twitch_function(f_env,Af,Lce,CT,RT,Fs)
T1 = CT*Lce^2+(CT*1/4)*f_env;
T2_temp = (RT + (RT*1/4)*Af)/Lce;
T2 = T2_temp/1.68;
t_twitch = 0:1/Fs:1;
f_1 = t_twitch./T1.*exp(1-t_twitch./T1);
f_2 = t_twitch./T2.*exp(1-t_twitch./T2);

twitch = [f_1(1:round(T1*Fs+1)) f_2(round(T2*Fs+1):end)];
twitch = twitch(1:length(t_twitch));

end

function Af = Af_slow_function(force,L,Y)
a_f = 0.56;
n_f0 = 2.1;
n_f1 = 5;
n_f = n_f0 + n_f1*(1/L-1);
Af = 1 - exp(-(Y*force/(a_f*n_f))^n_f);
end

function Af = Af_slow_correction_function(f_env,L,Y)
a_f = 0.46;
n_f0 = 2.17;
n_f1 = 6.1;
n_f = n_f0 + n_f1*(1/L-1);
Af = 1 - exp(-(Y*f_env/(a_f*n_f))^n_f);
Af = Af/f_env;
end


function Af = Af_fast_function(force,L,S)
a_f = 0.56;
n_f0 = 2.1;
n_f1 = 3.3;
n_f = n_f0 + n_f1*(1/L-1);
Af = 1 - exp(-(S*force/(a_f*n_f))^n_f);
end

function Af = Af_fast_correction_function(f_env,L,S)
a_f = 0.46;
n_f0 = 2.17;
n_f1 = 4;
n_f = n_f0 + n_f1*(1/L-1);
Af = 1 - exp(-(S*f_env/(a_f*n_f))^n_f);
Af = Af/f_env;
end


function spikeTrain = spikeTrainGenerator(t,Fs,freq)

spikeTrain = zeros(1,length(t));
ISI = round(1/freq*Fs);
numSpikes = round(length(t)/ISI);
index = [1:numSpikes]*ISI;
index(index>length(t)) = [];
spikeTrain(index) = 1;
spikeTrain(1) = 1;

end