close all
clear all
clc
Lce = 1;
Af = 0;
f_env = 0;

% F0 parameters
density = 1.06; % muscle density [g/cm^3]
L0 = 6.8; % optimal muscle length [cm]
mass = 0.15; % muscle mass [kg]
PCSA = (mass*1000)/(density*L0); % PCSA of muscle
sigma = 31.8; % specific tension
F0 = PCSA*sigma;
N_fibers = 272850; % number of muscle fibers
N_MU = 450; % number of motor units
i_MU = 1:N_MU; % index for motor units

%--------------------------------------------------------------------------
% Peak tetanus parameter
RP_MU = 100; %range of peak tension across motor untis in unit of fold
b_MU = log(RP_MU)/N_MU; %coefficient to establish a range of twich force values
P_MU = exp(b_MU*i_MU); %force generated by a motor unit as a function of its recruitment threshold=
fPCSA = PCSA/N_fibers; % fractional PCSA occupied by a single fiber
ni = P_MU/sum(P_MU)*N_fibers; % innervation number of each unit assuming that peak tension generated by each unit is proportional to innervation number
Pi = sigma*fPCSA*ni; % peak tetanus amplitude of each unit
Pi_half = Pi./2; % half of peak tetanus amplitude of each unit
% load('cor_factor')
% Pi = Pi.*cor_factor';
%--------------------------------------------------------------------------
% Recruitment parameters
%   Find recruitment threshold for individual units using exponential fit
F_pcsa_slow = 0.5; % fractional PSCA of slow-twitch motor units (0-1)
[error, index_slow] = min(abs(cumsum(Pi) - F0*F_pcsa_slow)); % index for the largest motor unit clacified as slow-twitch
Ur = 0.8; % recruitment threshold for the last recruited motor unit
Uth_1 = 0.01; % reruitment threshold for the first unit
f_RT = fit([1 N_MU]',[Uth_1 Ur]','exp1');
coeffs_f_RT = coeffvalues(f_RT);
U_th = coeffs_f_RT(1)*exp(coeffs_f_RT(2)*i_MU); % the resulting recruitment threshold for individual units

MFR_MU = 8; %muscle_parameter.MFR; %minimum firing rate constant for all motoneurons
PFR1_MU = 20; %the peak firing rate of the first recruited motoneuron in unit of impulse/sec
PFRD_MU = 40; %the desired difference in peak firing rates between the first and last units in unit of impulse/sec
RTEn_MU = U_th(end); %recruitment threshold of the last motor unit
PFR_MU = PFR1_MU + PFRD_MU * (U_th./RTEn_MU); %peak firing rate
FR_half = PFR_MU./2; % firing rate at which half of maximum tension is achieved

CT_n = 20;
FR_half_n = FR_half(end);
CT = 1.5*(CT_n*FR_half_n)./FR_half;
CT = CT - (CT(end)-CT_n);
CT = CT/1000;
RT = CT;

Fs = 10000;
t_twitch = 0:1/Fs:1;

testedUnits = [1 100 200 300 400]; 

for i = 1:length(testedUnits)
    unitN = testedUnits(i);
    [twitch_temp,T1,T2_temp] = twitch_function(f_env,Af,Lce,CT(unitN),RT(unitN),Fs);
    
    figure(1)
    plot(t_twitch,twitch_temp)
    xlabel('Time (sec)','FontSize',14)
    ylabel('Force (AU)','FontSize',14)
    hold on
    
end

legend('MU 1','MU 100','MU 200','MU 300','MU 400')

figure(2)
plot(i_MU,CT)
xlabel('i: MU Number','FontSize',14)
ylabel('Contraction Time (sec)','FontSize',14)

figure(3)
plot(i_MU,PFR_MU)
xlabel('i: MU Number','FontSize',14)
ylabel('PFR: Peak Firing Rate (Hz)','FontSize',14)

figure(4)
plot(i_MU,U_th)
xlabel('i: MU Number','FontSize',14)
ylabel('U_{th}: Recruitment Threshold','FontSize',14)


function [twitch,T1,T2_temp] = twitch_function(f_env,Af,Lce,CT,RT,Fs)
T1 = CT*Lce^2+(CT*1/4)*f_env;
T2_temp = (RT + (RT*1/4)*Af)/Lce;
T2 = T2_temp/1.68;
t_twitch = 0:1/Fs:1;
f_1 = t_twitch./T1.*exp(1-t_twitch./T1);
f_2 = t_twitch./T2.*exp(1-t_twitch./T2);

twitch = [f_1(1:round(T1*Fs+1)) f_2(round(T2*Fs+1):end)];
twitch = twitch(1:length(t_twitch));

end
